### ISSUE TITLE
The README.md states that there are recompiled bitstreams available in the bin directory but the bin directory does not exist

### ISSUE THREAD

**Issue by JamesTimothyMeech** [signaloid/C0-microSD-Hardware#1]
The README.md states: "You can also find two pre-compiled example bitstreams in the bin/ directory of this repository." but the bin directory does not exist in this repository or in the submodule.

**Comment by almidi** [comment]
We updated the repository to include Bootloader, Signaloid Core, and a blink bitstream in the `bin/` directory.
